language: node_js  #设置语言

node_js: stable  #设置相应的版本

install:
  - npm install  #安装hexo及插件

script:
  - hexo cl
  - hexo g

after_script:
  - cd ./public
  - git init
  - git config user.name "HenrayLuo"
  - git config user.email "HenrayLuo@gmail.com"
  - git add .
  - git commit -m "update site"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:gh-pages
# E: Build LifeCycle

branches:
  only:
    - master
env:
 global:
   - GH_REF: github.com/henrayluo/henrayluo.github.io.git
   - secure: "gTtp3j+gI4Mp4QTvWeB2ofg+YSs7Da1sBNkrFup9WgGir9/5Oafft8e3/JxK2D0dS5X4MloXmjVP1VqUKZ5GnEkXn4J1IciwGOl/KbTBSzAKGDYmUdLswPsRwc3ihvo/mkVNFkqoDeyHG632X3j5SvZkot16X2Jh7kCMF2Ik2qsPk299SM5AXKiXpIPyK0R8i58NVBOx5Nwx6giX7/+6xENdkGXR1nenwnyy3VatsUl31NSsy3YA1wjzXcQxc942QClH0cRZHYJpLg06sTEnqZt3IawEVI0Egs7sRrdqo8AzRarV76TI0F3S9hpCNBMQI1vp2Nx/1tjcAVirJvzzYM/duLBW3AKs0P7bCp31X4tryq+n3Wn/Kcko6DEcy6fBr1MS9uC9DValyC6l7cB6XqrMv/mkw2wo3Fk63o7yTMp8klcS1C5bdbhMoAYrsWh2Q3VPjiARyuAa84GVbISwi7sghGKV2BMcduslOtRTqq5eK7Woh5+geqTQS/jKjr4mIe5vKKZqjSL4ykM7XuFWGRDpwbDdTJkQ2qA2Z2DEZZrstfE7+k1JWBjh4P1YzSdzOa9h9I21+zIo36TILLtCQedMZfKPf6k2RrDlpe+Sm5KzqFLO6a3NB5uOV8c6JUCjTXNJmhgRW4wf0DFv6wvb87t9SaQU1KJ0HV/7PNP+YiE="
