language: node_js  #设置语言

node_js: #设置相应的版本
  - "7"
install:
  - npm install  #安装hexo及插件

script:
  - hexo cl
  - hexo g

after_script:
  - cd ./public
  - ls -al
  - git init
  - git config user.name "ray"
  - git config user.email "henrayluo@gmail.com"
  - git add .
  - git commit -m "update site"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master
# E: Build LifeCycle

branches:
  only:
    - blog
env:
 global:
   - GH_REF: github.com/henrayluo/henrayluo.github.io.git
   - secure: "OOWkkww+jkeMIqU+/iO2CapZYRHVulZUiG88+Ux/MwDZM5qVuyZGqxYadgMIHX77BPRZ+qY3Rns/Ks5AHgII5VyXLKtd+WOrCkhw5TnvuPjx89vwLYY7hK18Lv3TbCgrB21qd+D+6n0krErk/aD0/fPWmTwOjCjoGe8Cx0bo/Q0yCKXd3+MbxRWA4b9qtSRcKTXLF8gWHcJ9hsIBC3ske4mLYdTlJmTkZKzt7FiL6sAzP21IRJCir4XszsDgCXhn/0pqf4rsP0N1SxaXZtLQgfA19BtKykgTL6dY/lv/+y0G6AZ/2uFmXyFg+OiFgUPxaxZZythvQf9W7SC9lS76ujSW9+SXqzO5wnOHfQuTHYNl5kLafu7DKXjUziFl8BuX4p14JmzsdMxAxcnNU46YVqH+iBvSTjd5i8qOZGCzN/QWulcRSJkrri0q7s5aGv8Npn9wFlmv5psK5JV+V9Mvd/4V7OI0tqmihAQfr90IjtBB0AyaI/DWtrFQvRhro8PTEv4416fbvYkSB+XBuaPxxQnOl9jAxnQRcrO8xTQ/bj2WBZmMJmx9ytYBYPcAiqGiqU58YkKEu18DQWgPpGoKgj6q3nKnNfBLCjUn/kkuzqWqqAkdAxx6Y7yX7rXACYMLLqPKlJIbH+uE0IuIsyx4itIxV0S2ZxsiioOe6TqtlA0="
