language: node_js  #设置语言

node_js: stable  #设置相应的版本

install:
  - npm install  #安装hexo及插件

script:
  - hexo cl  #清除
  - hexo g  #生成

after_script:
  - cd ./public
  - git init
  - git config user.name "henrayluo"
  - git config user.email "henrayluo@gmail.com"
  - git add .
  - git commit -m "Update docs"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:gh-pages
# E: Build LifeCycle

branches:
  only:
    - master
env:
 global:
   - GH_REF: github.com/henrayluo/henrayluo.git
   - secure: "dLv1sEcBzmfmy+ax384jBOlnsyq56oEUxRHtjYsGh459YBT2K+051HLTvay5jUOW738KSb4uW+/AxY7YEUe1yXrLB5qmVbKwCdxaoh7P04TLR78LRGqPm16LfApAcbukg55C72vIqKyVu3+w2DXZqQ7t3KDZJfZON2wj68FYuY8ALEVg8r8UprHMEJTwLrdHtW2ykb6wxBfA8r2bwf03D4carpUob7EX/2WgLqf2BP2vGhf9Hgq8MifqrtsXbyX2SrpJyEjREYKrkhxI5VXkFh1+83elgtH6RZxZvh7UP51wCO8j3DD2nvgpap7rYNe1GbNhshq+j9x84p+lgpj15Qw1K70euYp6egu7e7fvRVhAdGHF5sk+y8bTts+PgUboGV7mPPKt+T6M9ZQ0T9CxXP00G25xIr/Jtnek69BAuRUAOIp7RYAVYUP7qAEs3Cn6TaLsXxrru7WnVJWX6j4q/SkiZaO8Boz7CCMMPis+hYj0dW9Z9TlH1t6ciyRbpjmuawUTIgdAn/LVdVSKezWd06egKTOLZr56GpWGD+8TUr93XWEME2K+Fydk/6rKJigKqBfPgt0Nq0uHRDeBe88NKY+ExaXa1/YRxW97OiBKV/L3le3qv1VkxTAS6Qvot+E/NBsd0NVoF2EoukrEJpV0Wa7kvb3rRn4boTuXv9nR6r8="
